#ifndef INCLUDE_GUARD
#define INCLUDE_GUARD

#define PROJECT_NAME "neoworld"
#define PROJECT_VER  "0.2.9"
#define PROJECT_VER_MAJOR "0"
#define PROJECT_VER_MINOR "2"
#define PTOJECT_VER_PATCH "9"
#define PTOJECT_GITHASH "c226486"

#endif // INCLUDE_GUARD
